# Generated by Django 2.2 on 2020-01-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='details',
            field=models.TextField(blank=True),
        ),
    ]
