# Generated by Django 2.0 on 2020-01-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='createdby',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
